#!/bin/sh

# ci_post_clone.sh
# This script runs after Xcode Cloud clones the repository.
# It injects environment variables into a generated xcconfig file
# so they are available at runtime via Info.plist.

set -e

echo "Generating Secrets.xcconfig from Xcode Cloud environment variables..."

CONFIG_FILE="$CI_PRIMARY_REPOSITORY_PATH/Sample/SwiftSample/Secrets.generated.xcconfig"

cat <<EOF > "$CONFIG_FILE"
// Auto-generated by ci_post_clone.sh — do not commit
FRESHCHAT_APP_ID = ${FRESHCHAT_APP_ID}
FRESHCHAT_APP_KEY = ${FRESHCHAT_APP_KEY}
FRESHCHAT_DOMAIN = ${FRESHCHAT_DOMAIN}
EOF

echo "Secrets.xcconfig generated at: $CONFIG_FILE"

# --- Dynamically set SPM branch to match the current CI branch ---
echo "Updating SPM package branch to: $CI_BRANCH"

PBXPROJ_FILE="$CI_PRIMARY_REPOSITORY_PATH/Sample/SwiftSample/SwiftSample.xcodeproj/project.pbxproj"

# Replace the branch value in the XCRemoteSwiftPackageReference requirement
sed -i '' "s/branch = [^;]*;/branch = $CI_BRANCH;/" "$PBXPROJ_FILE"

echo "SPM package branch updated to '$CI_BRANCH' in project.pbxproj"

# Update Package.resolved in-place — Xcode Cloud requires the file to exist at all times
# (automatic package resolution is disabled), so we never delete it.
# Instead, fetch the latest commit hash for the target branch and patch the file directly.
RESOLVED_FILE="$CI_PRIMARY_REPOSITORY_PATH/Sample/SwiftSample/SwiftSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"

echo "Fetching latest commit hash for branch '$CI_BRANCH'..."
NEW_REVISION=$(git ls-remote https://github.com/freshworks/freshchat-ios "refs/heads/$CI_BRANCH" | cut -f1)

if [ -z "$NEW_REVISION" ]; then
  echo "Error: Branch '$CI_BRANCH' not found in freshchat-ios repository"
  exit 1
fi

echo "Resolved '$CI_BRANCH' to commit: $NEW_REVISION"

sed -i '' "s/\"branch\" : \".*\"/\"branch\" : \"$CI_BRANCH\"/" "$RESOLVED_FILE"
sed -i '' "s/\"revision\" : \".*\"/\"revision\" : \"$NEW_REVISION\"/" "$RESOLVED_FILE"

echo "Package.resolved updated to branch '$CI_BRANCH' at $NEW_REVISION"
