#!/bin/sh

# ci_post_clone.sh
# This script runs after Xcode Cloud clones the repository.
# It injects environment variables into a generated xcconfig file
# so they are available at runtime via Info.plist.

set -e

echo "Generating Secrets.xcconfig from Xcode Cloud environment variables..."

CONFIG_FILE="$CI_PRIMARY_REPOSITORY_PATH/Sample/SwiftSample/Secrets.generated.xcconfig"

cat <<EOF > "$CONFIG_FILE"
// Auto-generated by ci_post_clone.sh — do not commit
FRESHCHAT_APP_ID = ${FRESHCHAT_APP_ID}
FRESHCHAT_APP_KEY = ${FRESHCHAT_APP_KEY}
FRESHCHAT_DOMAIN = ${FRESHCHAT_DOMAIN}
EOF

echo "Secrets.xcconfig generated at: $CONFIG_FILE"

# --- Dynamically set SPM branch to match the current CI branch ---
echo "Updating SPM package branch to: $CI_BRANCH"

PBXPROJ_FILE="$CI_PRIMARY_REPOSITORY_PATH/Sample/SwiftSample/SwiftSample.xcodeproj/project.pbxproj"

# Replace the branch value in the XCRemoteSwiftPackageReference requirement
sed -i '' "s/branch = \".*\";/branch = \"$CI_BRANCH\";/" "$PBXPROJ_FILE"

echo "SPM package branch updated to '$CI_BRANCH' in project.pbxproj"

# Remove Package.resolved to force Xcode to re-resolve with the updated branch
RESOLVED_FILE="$CI_PRIMARY_REPOSITORY_PATH/Sample/SwiftSample/SwiftSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
if [ -f "$RESOLVED_FILE" ]; then
  rm "$RESOLVED_FILE"
  echo "Removed Package.resolved to force fresh package resolution"
fi
